import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MouseTrail from "@/components/MouseTrail";
import { SmoothCursor } from "@/components/ui/smooth-cursor";
import ScrollProgress from "@/components/Scroll-Progress-bar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
      suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ScrollProgress height={5} className="bg-teal-600"/>
        {/* <MouseTrail  imageSrc="/vercel.svg" maxTrails={15} /> */}
        {children}
      </body>
    </html>
  );
}
